# Promise.try

Promise.try 这个提案用于简化同步和异步函数的统一处理。它将任意函数包装在一个 Promise 中，确保函数在当前调用栈中执行，并返回一个 Promise，处理可能的返回值或异常。

## 动机

- 现有问题：使用 Promise.resolve().then(f) 会导致函数 f 异步调用，而 new Promise(resolve => resolve(f())) 使用不便。
- 解决方案：Promise.try(f) 提供了简洁的 API，同步执行函数，并处理生成的 Promise。

## 主要功能

- 同步执行函数 f。
- 包装返回值或异常为 Promise，支持链式操作。

## 示例

同步函数：

```js
function syncFunction() {
  return 42;
}

Promise.try(syncFunction)
  .then(console.log) // 输出：42
  .catch(console.error);
```

异步函数：

```js
async function asyncFunction() {
  return 42;
}

Promise.try(asyncFunction)
  .then(console.log) // 输出：42
  .catch(console.error);
```

处理异常：

```js
function riskyFunction() {
  throw new Error("Error!");
}

Promise.try(riskyFunction).then(console.log).catch(console.error); // 输出：Error: Error!
```

## 链接

- 地址：https://github.com/tc39/proposal-promise-try
- http://cryto.net/~joepie91/blog/2016/05/11/what-is-promise-try-and-why-does-it-matter/
- https://twitter.com/RReverser/status/695678489937186816
